name: CI donbot standalone
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  push:
    branches:
      - master
#      - devel
  pull_request:
    branches:
      - master
      - devel
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        path: 'ros_ws/src/giskardpy'
        repository: SemRoCo/giskardpy
    - name: Checkout giskard msgs
      uses: actions/checkout@v3
      with:
        path: 'ros_ws/src/giskard_msgs'
        repository: SemRoCo/giskard_msgs
    - name: Checkout qpoases
      uses: actions/checkout@v3
      with:
        path: 'ros_ws/src/qpOASES'
        repository: SemRoCo/qpOASES
        ref: noetic
    - name: Checkout iai_robots
      uses: actions/checkout@v3
      with:
        path: 'ros_ws/src/iai_robots'
        repository: code-iai/iai_robots
        ref: noetic
    - name: Checkout iai_maps
      uses: actions/checkout@v3
      with:
        path: 'ros_ws/src/iai_maps'
        repository: code-iai/iai_maps
        ref: master
    - name: Setup Giskard workspace
      uses: betwo/github-setup-catkin@master
      env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        # Version range or exact version of ROS version to use, using SemVer's version range syntax.
        ros-version: noetic
        build-tool: 'catkin_tools'
        # Root directory of the catkin workspace
        workspace: $GITHUB_WORKSPACE/ros_ws
    - name: install python deps
      run: |
        sudo pip3 install numpy==1.23.4 pandas hypothesis
    - name: build Giskard
      run: |
        cd ros_ws
        catkin build
        echo 'export ROS_HOSTNAME=localhost' >> ~/.bashrc
        echo 'source $GITHUB_WORKSPACE/ros_ws/devel/setup.bash' >> ~/.bashrc
    - name: build betterpybullet
      run: |
        mkdir betterpybullet
        source $GITHUB_WORKSPACE/ros_ws/devel/setup.bash
        roscd giskardpy
        ./scripts/build_better_pybullet.sh /betterpybullet
    - name: start roscore
      run: |
        roscore &
    - name: donbot TestCartGoals
      run: |
        roscd giskardpy
        python3 -m pytest -s test/test_integration_donbot.py::TestCartGoals
    - name: donbot TestConstraints
      run: |
        roscd giskardpy
        python3 -m pytest -s test/test_integration_donbot.py::TestConstraints
    - name: donbot TestJointGoals
      run: |
        roscd giskardpy
        python3 -m pytest -s test/test_integration_donbot.py::TestJointGoals
#    - name: Setup upterm session
##      if: always()
#      if: failure()
#      uses: lhotari/action-upterm@v1
